Repository k8up-io/k8up, pull requests merged in 2020-12, with the labels that each got.

#170 Add e2e test with bats-detik
  .github/workflows/build.yml
  .gitignore
  Makefile
  README.md
  e2e/Makefile
  e2e/kind-config.yaml
  e2e/lib/detik.bash
  e2e/lib/k8up.bash
  e2e/lib/linter.bash
  e2e/lib/utils.bash
  e2e/lint.bats
  e2e/package-lock.json
  e2e/package.json
  e2e/test1.bats
  e2e/test1/deployment.yaml
  e2e/test1/kustomization.yaml
Labels: enhancement

#199 Fix 'tar: Error opening File' when `make intergration_test`
  Makefile
Labels: bug

#201 Fixes in backup.adoc
  docs/modules/ROOT/pages/backup.adoc
Labels: bug

#202 Fix Null Pointer Dereference
  handler/schedule.go
Labels: bug

#186 Add new smart schedules
  api/v1alpha1/schedule_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/apiextensions.k8s.io/v1/backup.appuio.ch_schedules.yaml
  config/crd/apiextensions.k8s.io/v1beta1/backup.appuio.ch_schedules.yaml
  config/samples/k8up_v1alpha1_schedule.yaml
  docs/modules/ROOT/examples/schedule-status.yaml
  docs/modules/ROOT/pages/explanations/missing-docs.adoc
  docs/modules/ROOT/pages/how-tos/optimize-schedules.adoc
  docs/modules/ROOT/pages/references/schedule-specification.adoc
  docs/modules/ROOT/partials/nav-howtos.adoc
  docs/modules/ROOT/partials/nav-reference.adoc
  handler/job.go
  handler/randomizer.go
  handler/randomizer_test.go
  handler/schedule.go
  handler/schedule_test.go
  scheduler/scheduler.go
Labels: enhancement

#242 Replace internal schedules when reconciling Schedule CRs
  api/v1alpha1/job_types.go
  handler/schedule.go
  scheduler/scheduler.go
  scheduler/scheduler_test.go
Labels: bug

#240 Fix listing of PreBackupPods in foreign namespaces
  prebackup/prebackup.go
  prebackup/prebackup_test.go
Labels: bug

#218 Add JobSucceeded Condition to Status fields
  docs/modules/ROOT/pages/how-tos/check-status.adoc
  executor/archive.go
  executor/backup.go
  executor/generic.go
  executor/prune.go
  executor/restore.go
  observer/observer.go
  observer/observer_test.go
Labels: enhancement

#245 Skip tagging and publishing of floating tags in prereleases
  .goreleaser.yml
Labels: change

#248 Replace Goreleaser changelog generator with PR-based generator
  .github/PULL_REQUEST_TEMPLATE.md
  .github/changelog-configuration.json
  .github/workflows/release.yml
  .gitignore
  .goreleaser.yml
  renovate.json
Labels: change

#250 Replace local registry by loading e2e images directly onto KIND cluster
  .github/workflows/build.yml
  Makefile
  e2e/kind-config.yaml
  e2e/test1.bats
  e2e/test1/deployment.yaml
  main.go
Labels: change

#249 Ignore existing prebackup deployments
  config/rbac/role.yaml
  controllers/backup_controller.go
  prebackup/prebackup.go
Labels: bug
