Repository k8up-io/k8up, pull requests merged in 2021-02, with the labels that each got.

#340 Fix "sha1sum command is not found" in e2e-tests on macOS
  Makefile.vars.mk
Labels: bug

#342 Speed up `make test`
  Makefile
Labels: change

#333 new CRD: EffectiveSchedule
  Makefile
  api/v1alpha1/common_types.go
  api/v1alpha1/effectiveschedule_types.go
  api/v1alpha1/schedule_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  cfg/config.go
  cfg/config_test.go
  config/crd/apiextensions.k8s.io/v1/base/backup.appuio.ch_effectiveschedules.yaml
  config/crd/apiextensions.k8s.io/v1/base/backup.appuio.ch_schedules.yaml
  config/crd/apiextensions.k8s.io/v1/kustomization.yaml
  config/crd/apiextensions.k8s.io/v1beta1/backup.appuio.ch_effectiveschedules.yaml
  config/crd/apiextensions.k8s.io/v1beta1/base/backup.appuio.ch_effectiveschedules.yaml
  config/crd/apiextensions.k8s.io/v1beta1/base/backup.appuio.ch_schedules.yaml
  config/crd/apiextensions.k8s.io/v1beta1/kustomization.yaml
  config/crd/patches/cainjection_in_effectiveschedules.yaml
  config/crd/patches/webhook_in_effectiveschedules.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  controllers/common_integration_test.go
  controllers/envsuite_test.go
  controllers/restore_integration_test.go
  controllers/schedule_controller.go
  controllers/schedule_controller_test.go
  controllers/schedule_it_test.go
  controllers/schedule_it_utils_test.go
  docs/modules/ROOT/assets/images/architecture.drawio.svg
  docs/modules/ROOT/examples/references/effective-schedule.yaml
  docs/modules/ROOT/examples/schedule-status.yaml
  docs/modules/ROOT/pages/explanations/what-has-changed-in-v1.adoc
  docs/modules/ROOT/pages/how-tos/optimize-schedules.adoc
  docs/modules/ROOT/pages/references/config-reference.adoc
  docs/modules/ROOT/pages/references/object-specifications.adoc
  docs/modules/ROOT/pages/references/schedule-specification.adoc
  docs/modules/ROOT/pages/references/status.adoc
  handler/effectiveschedule.go
  handler/effectiveschedule_test.go
  handler/schedule.go
  handler/schedule_test.go
  job/job.go
  scheduler/scheduler.go
Labels: change

#343 Use '%w' syntax in fmt.Errorf
  cfg/config.go
Labels: change

#345 Introduce BackendInterface and document more backend settings
  api/v1alpha1/backend.go
  api/v1alpha1/backend_test.go
  cfg/config.go
  config/crd/apiextensions.k8s.io/v1/base/backup.appuio.ch_schedules.yaml
  config/crd/apiextensions.k8s.io/v1beta1/base/backup.appuio.ch_schedules.yaml
  docs/modules/ROOT/pages/references/object-specifications.adoc
Labels: change

#347 Explain backupcommand for pods with same owner reference
  docs/modules/ROOT/pages/how-tos/application-aware-backups.adoc
Labels: documentation

#341 Check status of PreBackupPod Deployments after operator restart
  api/v1alpha1/effectiveschedule_types.go
  config/samples/k8up_v1alpha1_prebackuppod.yaml
  controllers/backup_integration_test.go
  controllers/envsuite_test.go
  prebackup/prebackup.go
Labels: bug

#348 Ensure linter checks for generated code too
  .github/workflows/lint.yml
  config/crd/apiextensions.k8s.io/v1/base/backup.appuio.ch_effectiveschedules.yaml
  config/crd/apiextensions.k8s.io/v1beta1/base/backup.appuio.ch_effectiveschedules.yaml
Labels: change

#346 Generate API reference documentation with generator
  Makefile
  Makefile.vars.mk
  docs/api-gen-config.yaml
  docs/api-templates/gv-details.tpl
  docs/api-templates/gv-list.tpl
  docs/api-templates/type-members.tpl
  docs/api-templates/type.tpl
  docs/modules/ROOT/pages/references/api-reference.adoc
  docs/modules/ROOT/pages/references/object-specifications.adoc
  docs/modules/ROOT/partials/nav-reference.adoc
  generate.go
  go.mod
  go.sum
  tools.go
Labels: documentation

#350 New K8up Logo
  README.md
  docs/images/logo.png
  docs/modules/ROOT/assets/images/k8up-logo-square.png
  docs/modules/ROOT/assets/images/k8up-logo-square.svg
  docs/modules/ROOT/assets/images/k8up-logo.png
  docs/modules/ROOT/assets/images/k8up-logo.svg
  docs/modules/ROOT/assets/images/k8up_logo.png
  docs/modules/ROOT/pages/explanations/ide.adoc
  docs/modules/ROOT/pages/index.adoc
Labels: documentation

#351 Add documentation to manage pod resources
  docs/modules/ROOT/pages/how-tos/manage-pod-resources.adoc
  docs/modules/ROOT/partials/nav-howtos.adoc
Labels: documentation

#349 Change logging key to avoid clash
  scheduler/scheduler.go
Labels: bug

#355 Fix change of random schedule not being applied
  api/v1alpha1/effectiveschedule_types.go
  config/crd/apiextensions.k8s.io/v1/base/backup.appuio.ch_effectiveschedules.yaml
  config/crd/apiextensions.k8s.io/v1beta1/base/backup.appuio.ch_effectiveschedules.yaml
  controllers/schedule_it_test.go
  controllers/schedule_it_utils_test.go
  docs/modules/ROOT/pages/references/api-reference.adoc
  handler/effectiveschedule.go
  handler/effectiveschedule_test.go
Labels: bug

#362 Pin mikepenz/release-changelog-builder-action to v1
  .github/workflows/release.yml
Labels: dependency

#364 Fix loading of Operator environment variables
  main.go
  main_test.go
Labels: bug

#363 Various maintainability improvements
  cfg/config.go
  cfg/config_test.go
  controllers/archive_controller.go
  controllers/backup_controller.go
  controllers/check_controller.go
  controllers/controller_setup.go
  controllers/job_controller.go
  controllers/prune_controller.go
  controllers/restore_controller.go
  controllers/schedule_controller.go
  go.mod
  main.go
Labels: change

#368 Fix wrong structure of samples
  config/samples/k8up_v1alpha1_backup.yaml
  config/samples/k8up_v1alpha1_check.yaml
  config/samples/k8up_v1alpha1_prune.yaml
  config/samples/k8up_v1alpha1_restore.yaml
  config/samples/k8up_v1alpha1_snapshot.yaml
Labels: documentation

#369 Refactor e2e tests
  e2e/definitions/deployment/deployment.yaml
  e2e/definitions/deployment/kustomization.yaml
  e2e/lib/k8up.bash
  e2e/lint.bats
  e2e/package-lock.json
  e2e/test-deployment.bats
  e2e/test1.bats
Labels: change

#352 Introduce ScheduleSpecInterface
  api/v1alpha1/archive_types.go
  api/v1alpha1/backend.go
  api/v1alpha1/backup_types.go
  api/v1alpha1/check_types.go
  api/v1alpha1/common_types.go
  api/v1alpha1/prune_types.go
  api/v1alpha1/restore_types.go
  docs/modules/ROOT/pages/references/api-reference.adoc
  handler/schedule.go
  scheduler/scheduler.go
Labels: change

#378 Simplify feature request template a bit
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: change

#380 Add missing finalizer RBAC rules
  config/rbac/role.yaml
  controllers/archive_controller.go
  controllers/backup_controller.go
  controllers/check_controller.go
  controllers/job_controller.go
  controllers/prune_controller.go
  controllers/restore_controller.go
  controllers/schedule_controller.go
Labels: bug

#377 Update Go to v1.16
  Makefile
  go.mod
  go.sum
Labels: dependency
