Repository k8up-io/k8up, pull requests merged in 2021-08, with the labels that each got.

#470 Add job history defaults to documentation
  docs/modules/ROOT/pages/references/config-reference.adoc
Labels: documentation

#471 Update to version `v1.2.0` in docs
  docs/antora.yml
  docs/modules/ROOT/examples/tutorial/scripts/1_setup.sh
  docs/modules/ROOT/pages/tutorials/tutorial.adoc
Labels: documentation

#472 Move main to cmd/operator
  Makefile
  cmd/operator/main.go
  cmd/operator/main_test.go
  docs/modules/ROOT/pages/explanations/ide.adoc
Labels: change

#473 Move library functions to new operator package
  api/v1alpha1/backend.go
  api/v1alpha1/backend_test.go
  cmd/operator/main.go
  cmd/operator/main_test.go
  controllers/archive_controller.go
  controllers/backup_controller.go
  controllers/backup_integration_test.go
  controllers/backup_it_utils_test.go
  controllers/check_controller.go
  controllers/check_integration_test.go
  controllers/envsuite_test.go
  controllers/job_controller.go
  controllers/prune_controller.go
  controllers/restore_controller.go
  controllers/schedule_controller.go
  controllers/schedule_it_test.go
  controllers/schedule_it_utils_test.go
  envtest/envtest.go
  operator/cfg/config.go
  operator/cfg/config_test.go
  operator/executor/archive.go
  operator/executor/backup.go
  operator/executor/backup_utils.go
  operator/executor/check.go
  operator/executor/cleaner/cleaner.go
  operator/executor/cleaner/cleaner_test.go
  operator/executor/generic.go
  operator/executor/generic_test.go
  operator/executor/prebackup.go
  operator/executor/prebackup_utils.go
  operator/executor/prune.go
  operator/executor/restore.go
  operator/executor/restore_test.go
  operator/executor/worker.go
  operator/handler/effectiveschedule.go
  operator/handler/effectiveschedule_test.go
  operator/handler/generic.go
  operator/handler/job.go
  operator/handler/randomizer.go
  operator/handler/randomizer_test.go
  operator/handler/schedule.go
  operator/handler/schedule_test.go
  operator/job/job.go
  operator/job/status.go
  operator/job/status_test.go
  operator/observer/observer.go
  operator/observer/observer_test.go
  operator/queue/execution.go
  operator/queue/execution_test.go
  operator/queue/priority.go
  operator/scheduler/scheduler.go
  operator/scheduler/scheduler_test.go
Labels: change

#486 Fix Makefile for docker-push target
  Makefile
Labels: change

#491 Regression: Exclude goland/vscode from git
  .gitignore
Labels: ignore

#489 Improve Code Quality and Maintainability
  Makefile
  README.md
  cmd/operator/main.go
  cmd/operator/main_test.go
  cmd/restic/integration_test.go
  cmd/restic/main.go
  common/targzipwriter.go
  common/targzipwriter_test.go
  docs/modules/ROOT/examples/tutorial/scripts/environment.sh
  go.mod
  go.sum
  restic/cli/check.go
  restic/cli/interfaces.go
  restic/cli/prune.go
  restic/cli/restore.go
  restic/cli/stats.go
  restic/logging/logging.go
  restic/s3/client.go
  restic/stats/handler.go
Labels: change
