Repository k8up-io/k8up, pull requests merged in 2021-03, with the labels that each got.

#383 Replace 'Succeeded' reason in PreBackupReady condition with 'Ready'
  docs/modules/ROOT/pages/references/status.adoc
  prebackup/prebackup.go
Labels: breaking

#372 E2E-Test Backup
  .gitignore
  README.md
  e2e/Makefile
  e2e/definitions/backup/backup.yaml
  e2e/definitions/backup/kustomization.yaml
  e2e/definitions/k8up/deployment.yaml
  e2e/definitions/k8up/kustomization.yaml
  e2e/definitions/kind/config.yaml
  e2e/definitions/minio/helm.yaml
  e2e/definitions/secrets/kustomization.yaml
  e2e/definitions/secrets/secrets.yaml
  e2e/definitions/subject/deployment.yaml
  e2e/definitions/subject/kustomization.yaml
  e2e/definitions/subject/pv.yaml
  e2e/definitions/subject/pvc.yaml
  e2e/kind.mk
  e2e/lib/k8up.bash
  e2e/test-00-deployment.bats
  e2e/test-01-backup.bats
Labels: change

#384 Rework job status and PreBackup handling
  api/v1alpha1/common_types.go
  api/v1alpha1/status.go
  controllers/archive_controller.go
  controllers/backup_controller.go
  controllers/backup_integration_test.go
  controllers/backup_it_utils_test.go
  controllers/check_controller.go
  controllers/envsuite_test.go
  controllers/prune_controller.go
  controllers/restore_controller.go
  controllers/schedule_it_test.go
  executor/backup.go
  executor/backup_utils.go
  executor/prebackup.go
  executor/prebackup_utils.go
  handler/effectiveschedule.go
  handler/generic.go
  handler/schedule.go
  job/status.go
  prebackup/prebackup.go
  prebackup/prebackup_test.go
Labels: bug

#386 Pin wrestic image for e2e-tests
  Makefile.vars.mk
  e2e/Makefile
  e2e/lib/k8up.bash
Labels: change

#388 Refactor e2e-test utils
  Makefile
  Makefile.vars.mk
  README.md
  docs/modules/ROOT/pages/references/object-specifications.adoc
  e2e/Makefile
  e2e/lib/k8up.bash
  e2e/test-01-backup.bats
Labels: change

#390 Verify the correctness of a backup
  e2e/definitions/subject/deployment.yaml
  e2e/test-01-backup.bats
Labels: change

#391 Update vshn/wrestic image to v0.2.2 in e2e-tests
  Makefile.vars.mk
Labels: dependency

#387 E2E-Test for Restore operation
  e2e/definitions/restore/kustomization.yaml
  e2e/definitions/restore/restore.yaml
  e2e/definitions/subject/deployment.yaml
  e2e/lib/k8up.bash
  e2e/lint.bats
  e2e/test-01-backup.bats
  e2e/test-02-restore.bats
Labels: change

#401 Better names for e2e tests
  e2e/definitions/operator/deployment.yaml
  e2e/definitions/operator/kustomization.yaml
  e2e/lib/k8up.bash
  e2e/lint.bats
  e2e/test-00-deployment.bats
  e2e/test-01-backup.bats
  e2e/test-02-restore.bats
Labels: change

#403 Fix pre-backup condition not being displayed after renaming it
  api/v1alpha1/backup_types.go
  config/crd/apiextensions.k8s.io/v1/base/backup.appuio.ch_backups.yaml
  config/crd/apiextensions.k8s.io/v1beta1/base/backup.appuio.ch_backups.yaml
Labels: bug

#400 Actually Perform the Cleanup of Checks
  controllers/check_integration_test.go
  controllers/envsuite_test.go
  docs/modules/ROOT/pages/explanations/ide.adoc
  executor/check.go
Labels: bug

#409 Document k8up annotations
  docs/modules/ROOT/pages/references/annotations.adoc
  docs/modules/ROOT/partials/nav-reference.adoc
  go.sum
Labels: documentation

#411 Enable 'go mod tidy' for renovate
  renovate.json
Labels: change

#412 Remove preserveUnknownFields in v1 PreBackupPod CRD
  config/crd/apiextensions.k8s.io/v1/base/backup.appuio.ch_prebackuppods.yaml
  generate.go
Labels: bug
