Repository k8up-io/k8up, pull requests merged in 2021-11, with the labels that each got.

#542 refactor: move from io/ioutil to io and os package
  cmd/restic/integration_test.go
  restic/cli/backup.go
  restic/cli/stats.go
Labels: change

#551 Rename prometheus metrics namespace from 'baas' to 'k8up'
  config/samples/prometheus/rules.yaml
  docs/modules/ROOT/pages/explanations/what-has-changed-in-v2.adoc
  docs/modules/ROOT/pages/how-tos/restore.adoc
  restic/cli/stats.go
Labels: bug

#560 Add CII Badge to README
  README.md
Labels: change

#558 Add CODEOWNERS file
  CODEOWNERS
Labels: documentation

#562 Add signoff to Renovate
  renovate.json
Labels: ignore

#564 Change license from BSD-3-Clause to Apache 2.0
  LICENSE
Labels: change

#565 Add PostgreSQL example
  docs/modules/ROOT/pages/how-tos/application-aware-backups.adoc
Labels: documentation
