Repository k8up-io/k8up, pull requests merged in 2021-07, with the labels that each got.

#451 Add a note about docs version bump on release
  docs/antora.yml
  docs/modules/ROOT/pages/explanations/release.adoc
  docs/modules/ROOT/partials/nav-explanation.adoc
Labels: documentation

#452 Remove duplicate keys initialDelaySeconds, timeoutSeconds
  docs/modules/ROOT/examples/tutorial/mariadb/deployment.yaml
Labels: bug

#457 Update kind to 0.11.1
  Makefile.vars.mk
Labels: dependency

#455 Validate and update tutorial
  docs/modules/ROOT/examples/schedule.yaml
  docs/modules/ROOT/examples/tutorial/backup.yaml
  docs/modules/ROOT/examples/tutorial/mariadb/deployment.yaml
  docs/modules/ROOT/examples/tutorial/minio/deployment.yaml
  docs/modules/ROOT/examples/tutorial/restore/wordpress.yaml
  docs/modules/ROOT/examples/tutorial/scripts/1_setup.sh
  docs/modules/ROOT/examples/tutorial/scripts/3_backup.sh
  docs/modules/ROOT/examples/tutorial/scripts/4_restore.sh
  docs/modules/ROOT/examples/tutorial/scripts/5_schedule.sh
  docs/modules/ROOT/examples/tutorial/scripts/customize.py
  docs/modules/ROOT/examples/tutorial/scripts/db_restore.sh
  docs/modules/ROOT/examples/tutorial/wordpress/pvc.yaml
  docs/modules/ROOT/pages/how-tos/backup.adoc
  docs/modules/ROOT/pages/tutorials/tutorial.adoc
Labels: documentation

#460 Validate tutorial
  docs/modules/ROOT/examples/tutorial/mariadb/deployment.yaml
  docs/modules/ROOT/examples/tutorial/scripts/4_restore.sh
  docs/modules/ROOT/pages/tutorials/tutorial.adoc
Labels: documentation

#462 Clean histories for successful and failed jobs separately
  .codeclimate.yml
  Makefile
  Makefile.vars.mk
  api/v1alpha1/archive_types.go
  api/v1alpha1/backup_types.go
  api/v1alpha1/check_types.go
  api/v1alpha1/history_limits_test.go
  api/v1alpha1/job_object.go
  api/v1alpha1/object_list_test.go
  api/v1alpha1/prune_types.go
  api/v1alpha1/restore_types.go
  api/v1alpha1/schedule_types.go
  api/v1alpha1/status.go
  api/v1alpha1/zz_generated.deepcopy.go
  cfg/config.go
  cfg/config_test.go
  config/crd/apiextensions.k8s.io/v1/base/backup.appuio.ch_archives.yaml
  config/crd/apiextensions.k8s.io/v1/base/backup.appuio.ch_backups.yaml
  config/crd/apiextensions.k8s.io/v1/base/backup.appuio.ch_checks.yaml
  config/crd/apiextensions.k8s.io/v1/base/backup.appuio.ch_prunes.yaml
  config/crd/apiextensions.k8s.io/v1/base/backup.appuio.ch_restores.yaml
  config/crd/apiextensions.k8s.io/v1/base/backup.appuio.ch_schedules.yaml
  config/crd/apiextensions.k8s.io/v1beta1/base/backup.appuio.ch_archives.yaml
  config/crd/apiextensions.k8s.io/v1beta1/base/backup.appuio.ch_backups.yaml
  config/crd/apiextensions.k8s.io/v1beta1/base/backup.appuio.ch_checks.yaml
  config/crd/apiextensions.k8s.io/v1beta1/base/backup.appuio.ch_prunes.yaml
  config/crd/apiextensions.k8s.io/v1beta1/base/backup.appuio.ch_restores.yaml
  config/crd/apiextensions.k8s.io/v1beta1/base/backup.appuio.ch_schedules.yaml
  config/samples/k8up_v1alpha1_backup.yaml
  config/samples/k8up_v1alpha1_schedule.yaml
  controllers/backup_integration_test.go
  controllers/check_integration_test.go
  controllers/restore_integration_test.go
  docs/modules/ROOT/examples/schedule.yaml
  docs/modules/ROOT/examples/tutorial/backup.yaml
  docs/modules/ROOT/pages/references/api-reference.adoc
  docs/modules/ROOT/pages/references/config-reference.adoc
  docs/modules/ROOT/pages/references/object-specifications.adoc
  docs/modules/ROOT/pages/tutorials/tutorial.adoc
  e2e/definitions/backup/backup.yaml
  e2e/definitions/restore/restore.yaml
  envtest/envtest.go
  envtest/rootpath.go
  executor/archive.go
  executor/backup.go
  executor/check.go
  executor/cleaner/cleaner.go
  executor/cleaner/cleaner_test.go
  executor/generic.go
  executor/prune.go
  executor/restore.go
  job/job.go
  job/status.go
  job/status_test.go
  scheduler/scheduler.go
Labels: enhancement

#468 Manage kind version via go.mod
  Makefile.vars.mk
  e2e/kind.mk
  go.mod
  go.sum
  tools.go
Labels: change

#463 Consistent job naming
  api/v1alpha1/archive_types.go
  api/v1alpha1/backup_types.go
  api/v1alpha1/check_types.go
  api/v1alpha1/job_name_test.go
  api/v1alpha1/job_object.go
  api/v1alpha1/prune_types.go
  api/v1alpha1/restore_types.go
  api/v1alpha1/schedule_types.go
  controllers/backup_it_utils_test.go
  controllers/check_integration_test.go
  executor/generic.go
  job/job.go
Labels: change
