Repository k8up-io/k8up, pull requests merged in 2021-09, with the labels that each got.

#492 Upgrade Go to v1.17
  Makefile.vars.mk
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/restic/integration_test.go
  controllers/backup_integration_test.go
  controllers/backup_it_utils_test.go
  controllers/check_integration_test.go
  controllers/restore_integration_test.go
  controllers/schedule_it_test.go
  controllers/schedule_it_utils_test.go
  e2e/lib/k8up.bash
  envtest/envsuite.go
  go.mod
  go.sum
  operator/executor/cleaner/cleaner_integration_test.go
  operator/executor/restore_test.go
  operator/queue/execution_test.go
  tools.go
Labels: dependency

#494 Unified Logging
  Makefile
  Makefile.vars.mk
  cmd/k8up/main.go
  cmd/logger.go
  cmd/operator/main.go
  cmd/restic/main.go
Labels: change

#495 Unified Command Line Interface
  Makefile
  cmd/operator/main.go
  cmd/operator/main_test.go
  cmd/restic/integration_test.go
  cmd/restic/main.go
  controllers/archive_controller.go
  controllers/backup_controller.go
  controllers/check_controller.go
  controllers/prune_controller.go
  controllers/restore_controller.go
  controllers/schedule_controller.go
  docs/docs.mk
  docs/modules/ROOT/pages/references/config-reference.adoc
  docs/modules/ROOT/pages/references/usage/k8up.txt
  docs/modules/ROOT/pages/references/usage/operator.txt
  docs/modules/ROOT/pages/references/usage/restic.txt
  envtest/envsuite.go
  go.mod
  go.sum
  operator/cfg/config.go
  operator/cfg/config_test.go
  operator/executor/cleaner/cleaner.go
  operator/handler/schedule_test.go
  operator/queue/execution.go
  restic/cfg/config.go
  restic/cli/backup.go
  restic/cli/flags.go
  restic/cli/prune.go
  restic/cli/restic.go
  restic/cli/restore.go
  restic/cli/stats.go
  restic/cli/stdinbackup.go
  restic/kubernetes/config.go
Labels: change

#496 Fix include of CLI help text
  docs/docs.mk
  docs/modules/ROOT/examples/usage/k8up.txt
  docs/modules/ROOT/examples/usage/operator.txt
  docs/modules/ROOT/examples/usage/restic.txt
  docs/modules/ROOT/pages/references/config-reference.adoc
Labels: documentation

#498 Improve Architecture Documentation
  cmd/restic/main.go
  docs/k8up.adoc
  docs/modules/ROOT/examples/usage/restic.txt
  docs/modules/ROOT/pages/explanations/architecture.adoc
  docs/modules/ROOT/pages/how-tos/manage-pod-resources.adoc
  docs/modules/ROOT/pages/references/annotations.adoc
  docs/modules/ROOT/pages/references/operator-config-reference.adoc
  docs/modules/ROOT/pages/references/restic-config-reference.adoc
  docs/modules/ROOT/partials/nav-reference.adoc
  restic/cfg/config.go
Labels: documentation

#505 set version to master for Antora
  docs/antora.yml
Labels: documentation

#499 Add podSecurityContext to Schedule and schedulable actions
  api/v1alpha1/archive_types.go
  api/v1alpha1/backup_types.go
  api/v1alpha1/check_types.go
  api/v1alpha1/job_object.go
  api/v1alpha1/prune_types.go
  api/v1alpha1/restore_types.go
  api/v1alpha1/runnable_types.go
  api/v1alpha1/schedule_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/k8up/main.go
  config/crd/apiextensions.k8s.io/v1/base/backup.appuio.ch_archives.yaml
  config/crd/apiextensions.k8s.io/v1/base/backup.appuio.ch_backups.yaml
  config/crd/apiextensions.k8s.io/v1/base/backup.appuio.ch_checks.yaml
  config/crd/apiextensions.k8s.io/v1/base/backup.appuio.ch_prunes.yaml
  config/crd/apiextensions.k8s.io/v1/base/backup.appuio.ch_restores.yaml
  config/crd/apiextensions.k8s.io/v1/base/backup.appuio.ch_schedules.yaml
  config/crd/apiextensions.k8s.io/v1beta1/base/backup.appuio.ch_archives.yaml
  config/crd/apiextensions.k8s.io/v1beta1/base/backup.appuio.ch_backups.yaml
  config/crd/apiextensions.k8s.io/v1beta1/base/backup.appuio.ch_checks.yaml
  config/crd/apiextensions.k8s.io/v1beta1/base/backup.appuio.ch_prunes.yaml
  config/crd/apiextensions.k8s.io/v1beta1/base/backup.appuio.ch_restores.yaml
  config/crd/apiextensions.k8s.io/v1beta1/base/backup.appuio.ch_schedules.yaml
  controllers/backup_integration_test.go
  controllers/backup_it_utils_test.go
  docs/modules/ROOT/pages/references/api-reference.adoc
  e2e/definitions/backup/backup.yaml
  e2e/definitions/restore/restore.yaml
  e2e/lib/k8up.bash
  operator/handler/schedule.go
  operator/job/job.go
Labels: enhancement

#497 Replace vshn/wrestic with unified vshn/k8up Docker image
  .dockerignore
  .goreleaser.yml
  Dockerfile
  Makefile
  Makefile.restic-integration.mk
  Makefile.vars.mk
  README.md
  api/v1alpha1/backup_types.go
  cmd/operator/main.go
  cmd/restic/main.go
  config/crd/apiextensions.k8s.io/v1/base/backup.appuio.ch_backups.yaml
  config/crd/apiextensions.k8s.io/v1/base/backup.appuio.ch_schedules.yaml
  config/crd/apiextensions.k8s.io/v1beta1/base/backup.appuio.ch_backups.yaml
  config/crd/apiextensions.k8s.io/v1beta1/base/backup.appuio.ch_schedules.yaml
  docs/modules/ROOT/examples/usage/operator.txt
  docs/modules/ROOT/pages/explanations/architecture.adoc
  docs/modules/ROOT/pages/explanations/ide.adoc
  docs/modules/ROOT/pages/explanations/missing-docs.adoc
  docs/modules/ROOT/pages/references/api-reference.adoc
  docs/modules/ROOT/pages/references/object-specifications.adoc
  e2e/Makefile
  e2e/definitions/operator/deployment.yaml
  e2e/lib/k8up.bash
  envtest/envsuite.go
  operator/cfg/config.go
  operator/job/job.go
  restic/cli/restore.go
  wrestic/wrestic.sh
Labels: change, breaking, wrestic

#511 Changes 'k8up.syn.tools/' to 'k8up.io/' for k8s annotations
  api/v1alpha1/common_types.go
  api/v1alpha1/schedule_types.go
  cmd/operator/main.go
  config/crd/patches/cainjection_in_archives.yaml
  config/crd/patches/cainjection_in_backups.yaml
  config/crd/patches/cainjection_in_checks.yaml
  config/crd/patches/cainjection_in_prebackuppods.yaml
  config/crd/patches/cainjection_in_prunes.yaml
  config/crd/patches/cainjection_in_restores.yaml
  config/crd/patches/cainjection_in_schedules.yaml
  config/crd/patches/cainjection_in_snapshots.yaml
  config/crd/patches/webhook_in_archives.yaml
  config/crd/patches/webhook_in_backups.yaml
  config/crd/patches/webhook_in_checks.yaml
  config/crd/patches/webhook_in_prebackuppods.yaml
  config/crd/patches/webhook_in_prunes.yaml
  config/crd/patches/webhook_in_restores.yaml
  config/crd/patches/webhook_in_schedules.yaml
  config/crd/patches/webhook_in_snapshots.yaml
  config/samples/deployments/galera.yaml
  config/samples/deployments/mariadb.yaml
  config/samples/deployments/mongodb.yaml
  config/samples/deployments/pvc-example.yaml
  docs/modules/ROOT/assets/attachments/slides_embedded.html
  docs/modules/ROOT/examples/tutorial/mariadb/deployment.yaml
  docs/modules/ROOT/examples/tutorial/wordpress/pvc.yaml
  docs/modules/ROOT/examples/usage/operator.txt
  docs/modules/ROOT/pages/explanations/architecture.adoc
  docs/modules/ROOT/pages/how-tos/application-aware-backups.adoc
  docs/modules/ROOT/pages/how-tos/check-status.adoc
  docs/modules/ROOT/pages/how-tos/prebackuppod.adoc
  docs/modules/ROOT/pages/how-tos/restore.adoc
  docs/modules/ROOT/pages/how-tos/schedules.adoc
  docs/modules/ROOT/pages/references/annotations.adoc
  docs/modules/ROOT/pages/tutorials/tutorial.adoc
  e2e/definitions/annotated-subject/deployment.yaml
  envtest/envsuite.go
  operator/executor/prebackup_utils.go
  operator/handler/job.go
  operator/handler/schedule.go
Labels: change, breaking

#500 How to Upgrade to v2
  docs/modules/ROOT/pages/explanations/what-has-changed-in-v1.adoc
  docs/modules/ROOT/pages/explanations/what-has-changed-in-v2.adoc
  docs/modules/ROOT/pages/how-tos/upgrade.adoc
  docs/modules/ROOT/partials/nav-explanation.adoc
Labels: documentation

#514 De-partialize documentation navigation
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/partials/nav-explanation.adoc
  docs/modules/ROOT/partials/nav-howtos.adoc
  docs/modules/ROOT/partials/nav-reference.adoc
  docs/modules/ROOT/partials/nav-tutorials.adoc
Labels: documentation

#515 Update codeclimate test reporter id
  .github/workflows/test.yml
Labels: change

#516 Update path to slides in documentation
  docs/modules/ROOT/pages/tutorials/presentations.adoc
Labels: documentation

#517 Automate the release of documentation for Antora
  .github/workflows/docs.yml
  docs/modules/ROOT/nav.adoc
Labels: change

#518 Fix the docs git commit step
  .github/workflows/docs.yml
Labels: change

#525 Fixes link to k8up helm chart in docs
  docs/modules/ROOT/pages/how-tos/upgrade.adoc
  docs/modules/ROOT/pages/index.adoc
Labels: documentation

#527 Translate the ISSUE_TEMPLATEs to the GitHub Form Schema
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: ignore

#526 Explain K8up Backup Methods
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/explanations/backup.adoc
Labels: documentation

#510 ARM64 K8up
  .dockerignore
  .github/workflows/master.yml
  .github/workflows/release.yml
  .goreleaser.yml
  Dockerfile
  Makefile
  Makefile.vars.mk
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/explanations/supported-cpus.adoc
  fetch_restic.sh
  go.mod
  go.sum
  tools.go
Labels: enhancement

#531 Send post webhook even if backup dir does not exist
  restic/cli/backup.go
Labels: bug
