Repository k8up-io/k8up, pull requests merged in 2021-05, with the labels that each got.

#425 Add a new section "About" in documentation
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/about/code_of_conduct.adoc
  docs/modules/ROOT/pages/about/community.adoc
  docs/modules/ROOT/pages/about/contribution_guide.adoc
  docs/modules/ROOT/pages/about/roadmap.adoc
  docs/modules/ROOT/pages/about/visual_design.adoc
Labels: documentation

#430 Migrate setup-envtest.sh to setup-envtest util
  Makefile
  config/crd/apiextensions.k8s.io/v1/base/backup.appuio.ch_archives.yaml
  config/crd/apiextensions.k8s.io/v1/base/backup.appuio.ch_backups.yaml
  config/crd/apiextensions.k8s.io/v1/base/backup.appuio.ch_checks.yaml
  config/crd/apiextensions.k8s.io/v1/base/backup.appuio.ch_effectiveschedules.yaml
  config/crd/apiextensions.k8s.io/v1/base/backup.appuio.ch_prebackuppods.yaml
  config/crd/apiextensions.k8s.io/v1/base/backup.appuio.ch_prunes.yaml
  config/crd/apiextensions.k8s.io/v1/base/backup.appuio.ch_restores.yaml
  config/crd/apiextensions.k8s.io/v1/base/backup.appuio.ch_schedules.yaml
  config/crd/apiextensions.k8s.io/v1/base/backup.appuio.ch_snapshots.yaml
  config/crd/apiextensions.k8s.io/v1beta1/base/backup.appuio.ch_archives.yaml
  config/crd/apiextensions.k8s.io/v1beta1/base/backup.appuio.ch_backups.yaml
  config/crd/apiextensions.k8s.io/v1beta1/base/backup.appuio.ch_checks.yaml
  config/crd/apiextensions.k8s.io/v1beta1/base/backup.appuio.ch_effectiveschedules.yaml
  config/crd/apiextensions.k8s.io/v1beta1/base/backup.appuio.ch_prebackuppods.yaml
  config/crd/apiextensions.k8s.io/v1beta1/base/backup.appuio.ch_prunes.yaml
  config/crd/apiextensions.k8s.io/v1beta1/base/backup.appuio.ch_restores.yaml
  config/crd/apiextensions.k8s.io/v1beta1/base/backup.appuio.ch_schedules.yaml
  config/crd/apiextensions.k8s.io/v1beta1/base/backup.appuio.ch_snapshots.yaml
  go.mod
  go.sum
  tools.go
Labels: bug

#431 New configuration variable to pass options to restic
  cfg/config.go
  docs/modules/ROOT/pages/references/config-reference.adoc
  executor/generic.go
Labels: enhancement

#434 Pin quay.io/vshn/wrestic to latest
  Makefile.vars.mk
Labels: dependency
