Repository k8up-io/k8up, pull requests merged in 2021-01, with the labels that each got.

#253 Show link to changelog in the docs
  docs/modules/ROOT/nav.adoc
Labels: documentation

#252 Display number of changes since which tag in the changelog
  .github/changelog-configuration.json
Labels: change

#254 Convert architecture from png to svg and include in documentation
  architecture.png
  docs/modules/ROOT/assets/images/architecture.drawio.svg
  docs/modules/ROOT/pages/explanations/architecture.adoc
Labels: documentation

#258 Ensure backwards compatibility of GLOBALSECRETACCESSKEY variable
  cfg/config.go
Labels: bug

#255 Separate e2e tests and KIND from main Makefile
  .github/workflows/build.yml
  Makefile
  Makefile.vars.mk
  README.md
  e2e/Makefile
  e2e/kind.mk
Labels: change

#259 Add junit reporting for e2e tests
  .github/workflows/build.yml
  e2e/.gitignore
  e2e/Makefile
Labels: change

#262 Document Kustomize installation instructions
  config/auth-proxy/auth_proxy_client_clusterrole.yaml
  config/auth-proxy/auth_proxy_role.yaml
  config/auth-proxy/auth_proxy_role_binding.yaml
  config/auth-proxy/auth_proxy_service.yaml
  config/auth-proxy/kustomization.yaml
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manager/manager.yaml
  config/namespace/kustomization.yaml
  config/namespace/namespace.yaml
  config/rbac/kustomization.yaml
  docs/modules/ROOT/examples/howtos/kustomization.yaml
  docs/modules/ROOT/pages/how-tos/installation.adoc
  e2e/test1/kustomization.yaml
Labels: documentation

#267 Better distinguish between non-standard and k8up generative schedules
  docs/modules/ROOT/pages/references/schedule-specification.adoc
Labels: documentation

#268 Avoid reconciliation loops with predicates
  controllers/archive_controller.go
  controllers/backup_controller.go
  controllers/check_controller.go
  controllers/prune_controller.go
  controllers/restore_controller.go
  controllers/schedule_controller.go
Labels: change

#260 Pass Scheduler Backend Config to Childresources
  api/v1alpha1/backup_types.go
  api/v1alpha1/check_types.go
  api/v1alpha1/common_types.go
  api/v1alpha1/job_types.go
  api/v1alpha1/prune_types.go
  api/v1alpha1/restore_types.go
  api/v1alpha1/runnable_types.go
  api/v1alpha1/schedule_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/apiextensions.k8s.io/v1/backup.appuio.ch_archives.yaml
  config/crd/apiextensions.k8s.io/v1/backup.appuio.ch_checks.yaml
  config/crd/apiextensions.k8s.io/v1/backup.appuio.ch_prunes.yaml
  config/crd/apiextensions.k8s.io/v1/backup.appuio.ch_restores.yaml
  config/crd/apiextensions.k8s.io/v1/backup.appuio.ch_schedules.yaml
  config/crd/apiextensions.k8s.io/v1beta1/backup.appuio.ch_archives.yaml
  config/crd/apiextensions.k8s.io/v1beta1/backup.appuio.ch_checks.yaml
  config/crd/apiextensions.k8s.io/v1beta1/backup.appuio.ch_prunes.yaml
  config/crd/apiextensions.k8s.io/v1beta1/backup.appuio.ch_restores.yaml
  config/crd/apiextensions.k8s.io/v1beta1/backup.appuio.ch_schedules.yaml
  docs/modules/ROOT/pages/references/schedule-specification.adoc
  executor/restore_test.go
  handler/randomizer.go
  handler/randomizer_test.go
  handler/schedule.go
  handler/schedule_test.go
  queue/execution.go
  scheduler/scheduler.go
Labels: bug

#266 Fix Check Job Creation escapade
  executor/archive.go
  executor/check.go
  scheduler/scheduler.go
Labels: bug

#275 Improve failure handling in GH e2e report workflow
  .github/workflows/build.yml
Labels: change

#269 Load the e2e image into KIND in its own make-target
  Makefile
  Makefile.vars.mk
  e2e/Makefile
  e2e/test1.bats
Labels: change

#279 Show partial release notes for PreReleases
  .github/workflows/release.yml
Labels: change

#280 Fix Application of Global Memory Limit
  cfg/config.go
Labels: bug

#289 Add K8up viewer and editor roles to default built-in roles
  config/rbac/archive_editor_role.yaml
  config/rbac/archive_viewer_role.yaml
  config/rbac/backup_editor_role.yaml
  config/rbac/backup_viewer_role.yaml
  config/rbac/check_editor_role.yaml
  config/rbac/check_viewer_role.yaml
  config/rbac/consolidated_editor_role.yaml
  config/rbac/consolidated_viewer_role.yaml
  config/rbac/kustomization.yaml
  config/rbac/prebackuppod_editor_role.yaml
  config/rbac/prebackuppod_viewer_role.yaml
  config/rbac/prebackuppods_editor_role.yaml
  config/rbac/prebackuppods_viewer_role.yaml
  config/rbac/prune_editor_role.yaml
  config/rbac/prune_viewer_role.yaml
  config/rbac/restore_editor_role.yaml
  config/rbac/restore_viewer_role.yaml
  config/rbac/schedule_editor_role.yaml
  config/rbac/schedule_viewer_role.yaml
  config/rbac/snapshot_editor_role.yaml
  config/rbac/snapshot_viewer_role.yaml
  config/rbac/snapshots_editor_role.yaml
  config/rbac/snapshots_viewer_role.yaml
Labels: change

#295 Add preserveUnknownFields to generated PreBackupPod CRD
  config/crd/apiextensions.k8s.io/v1/backup.appuio.ch_prebackuppods.yaml
  config/crd/apiextensions.k8s.io/v1beta1/backup.appuio.ch_prebackuppods.yaml
  generate.go
Labels: bug

#282 Document missing environment variables
  docs/modules/ROOT/pages/references/config-reference.adoc
Labels: documentation

#283 Upgrade of Operator SDK to 1.3.0 / Kubebuilder to v3
  Dockerfile
  PROJECT
  config/manager/manager.yaml
  config/rbac/leader_election_role.yaml
Labels: enhancement

#296 Upgrade to controller-runtime 0.8 and K8s 1.20
  .github/workflows/build.yml
  Makefile
  Makefile.vars.mk
  README.md
  api/v1alpha1/groupversion_info.go
  config/crd/apiextensions.k8s.io/v1/backup.appuio.ch_prebackuppods.yaml
  config/crd/apiextensions.k8s.io/v1beta1/backup.appuio.ch_prebackuppods.yaml
  config/rbac/role.yaml
  controllers/archive_controller.go
  controllers/backup_controller.go
  controllers/check_controller.go
  controllers/job_controller.go
  controllers/prune_controller.go
  controllers/restore_controller.go
  controllers/schedule_controller.go
  executor/generic.go
  go.mod
  go.sum
  job/job.go
  scheduler/scheduler.go
Labels: dependency

#302 Rename new global environment vars
  cfg/config.go
  docs/modules/ROOT/pages/references/config-reference.adoc
Labels: change

#307 Add config option to enable verbose logging and set default to 'info'
  Makefile
  cfg/config.go
  docs/modules/ROOT/pages/references/config-reference.adoc
  e2e/test1/deployment.yaml
  go.mod
  main.go
Labels: change

#311 Change default backup image to quay.io/vshn/wrestic
  cfg/config.go
  docs/modules/ROOT/pages/references/config-reference.adoc
  executor/restore_test.go
Labels: breaking

#312 Avoid name clash by using scheduler name as prefix and random suffix
  executor/restore_test.go
  job/job.go
  scheduler/scheduler.go
  scheduler/scheduler_test.go
Labels: bug

#308 Introduce reasons and consolidate status conditions
  api/v1alpha1/archive_types.go
  api/v1alpha1/backup_types.go
  api/v1alpha1/check_types.go
  api/v1alpha1/common_types.go
  api/v1alpha1/prune_types.go
  api/v1alpha1/restore_types.go
  api/v1alpha1/schedule_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/apiextensions.k8s.io/v1/backup.appuio.ch_archives.yaml
  config/crd/apiextensions.k8s.io/v1/backup.appuio.ch_backups.yaml
  config/crd/apiextensions.k8s.io/v1/backup.appuio.ch_checks.yaml
  config/crd/apiextensions.k8s.io/v1/backup.appuio.ch_prunes.yaml
  config/crd/apiextensions.k8s.io/v1/backup.appuio.ch_restores.yaml
  config/crd/apiextensions.k8s.io/v1/backup.appuio.ch_schedules.yaml
  config/crd/apiextensions.k8s.io/v1beta1/backup.appuio.ch_archives.yaml
  config/crd/apiextensions.k8s.io/v1beta1/backup.appuio.ch_backups.yaml
  config/crd/apiextensions.k8s.io/v1beta1/backup.appuio.ch_checks.yaml
  config/crd/apiextensions.k8s.io/v1beta1/backup.appuio.ch_prunes.yaml
  config/crd/apiextensions.k8s.io/v1beta1/backup.appuio.ch_restores.yaml
  config/crd/apiextensions.k8s.io/v1beta1/backup.appuio.ch_schedules.yaml
  config/samples/k8up_v1alpha1_schedule.yaml
  docs/modules/ROOT/pages/references/status.adoc
  docs/modules/ROOT/partials/nav-reference.adoc
  executor/archive.go
  executor/backup.go
  executor/check.go
  executor/generic.go
  executor/prune.go
  executor/restore.go
  go.mod
  go.sum
  handler/job.go
  handler/schedule.go
  job/job.go
  job/status.go
  prebackup/prebackup.go
Labels: enhancement

#303 Document upgrade process for 0.x to 1.x
  docs/modules/ROOT/pages/explanations/missing-docs.adoc
  docs/modules/ROOT/pages/explanations/supported-k8s-versions.adoc
  docs/modules/ROOT/pages/explanations/what-has-changed-in-v1.adoc
  docs/modules/ROOT/pages/how-tos/upgrade.adoc
  docs/modules/ROOT/partials/nav-explanation.adoc
  docs/modules/ROOT/partials/nav-howtos.adoc
Labels: documentation

#313 Print Schedule ref and status conditions in kubectl
  api/v1alpha1/archive_types.go
  api/v1alpha1/backup_types.go
  api/v1alpha1/check_types.go
  api/v1alpha1/prune_types.go
  api/v1alpha1/restore_types.go
  config/crd/apiextensions.k8s.io/v1/backup.appuio.ch_archives.yaml
  config/crd/apiextensions.k8s.io/v1/backup.appuio.ch_backups.yaml
  config/crd/apiextensions.k8s.io/v1/backup.appuio.ch_checks.yaml
  config/crd/apiextensions.k8s.io/v1/backup.appuio.ch_prunes.yaml
  config/crd/apiextensions.k8s.io/v1/backup.appuio.ch_restores.yaml
  config/crd/apiextensions.k8s.io/v1beta1/backup.appuio.ch_archives.yaml
  config/crd/apiextensions.k8s.io/v1beta1/backup.appuio.ch_backups.yaml
  config/crd/apiextensions.k8s.io/v1beta1/backup.appuio.ch_checks.yaml
  config/crd/apiextensions.k8s.io/v1beta1/backup.appuio.ch_prunes.yaml
  config/crd/apiextensions.k8s.io/v1beta1/backup.appuio.ch_restores.yaml
  config/samples/secrets.yaml
  docs/modules/ROOT/pages/how-tos/check-status.adoc
  executor/generic.go
Labels: enhancement

#330 Convert executor/restore_test.go to unit test
  controllers/suite_test.go
  executor/executor_suite_test.go
  executor/restore.go
  executor/restore_test.go
  go.mod
  go.sum
Labels: change

#310 Introduce Integration Tests using envtest
  .github/workflows/test.yml
  Makefile
  Makefile.vars.mk
  config/crd/apiextensions.k8s.io/v1/base/backup.appuio.ch_archives.yaml
  config/crd/apiextensions.k8s.io/v1/base/backup.appuio.ch_backups.yaml
  config/crd/apiextensions.k8s.io/v1/base/backup.appuio.ch_checks.yaml
  config/crd/apiextensions.k8s.io/v1/base/backup.appuio.ch_prebackuppods.yaml
  config/crd/apiextensions.k8s.io/v1/base/backup.appuio.ch_prunes.yaml
  config/crd/apiextensions.k8s.io/v1/base/backup.appuio.ch_restores.yaml
  config/crd/apiextensions.k8s.io/v1/base/backup.appuio.ch_schedules.yaml
  config/crd/apiextensions.k8s.io/v1/base/backup.appuio.ch_snapshots.yaml
  config/crd/apiextensions.k8s.io/v1/kustomization.yaml
  config/crd/apiextensions.k8s.io/v1beta1/base/backup.appuio.ch_archives.yaml
  config/crd/apiextensions.k8s.io/v1beta1/base/backup.appuio.ch_backups.yaml
  config/crd/apiextensions.k8s.io/v1beta1/base/backup.appuio.ch_checks.yaml
  config/crd/apiextensions.k8s.io/v1beta1/base/backup.appuio.ch_prebackuppods.yaml
  config/crd/apiextensions.k8s.io/v1beta1/base/backup.appuio.ch_prunes.yaml
  config/crd/apiextensions.k8s.io/v1beta1/base/backup.appuio.ch_restores.yaml
  config/crd/apiextensions.k8s.io/v1beta1/base/backup.appuio.ch_schedules.yaml
  config/crd/apiextensions.k8s.io/v1beta1/base/backup.appuio.ch_snapshots.yaml
  config/crd/apiextensions.k8s.io/v1beta1/kustomization.yaml
  controllers/common_integration_test.go
  controllers/restore_integration_test.go
  docs/modules/ROOT/pages/explanations/ide.adoc
  docs/modules/ROOT/partials/nav-explanation.adoc
  generate.go
  go.mod
  go.sum
Labels: change
