Repository k8up-io/k8up, pull requests merged in 2022-05, with the labels that each got.

#657 Add 'envFrom' generic configuration for backend spec
  api/v1/backend.go
  api/v1/backend_test.go
  api/v1/runnable_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/apiextensions.k8s.io/v1/base/k8up.io_archives.yaml
  config/crd/apiextensions.k8s.io/v1/base/k8up.io_backups.yaml
  config/crd/apiextensions.k8s.io/v1/base/k8up.io_checks.yaml
  config/crd/apiextensions.k8s.io/v1/base/k8up.io_prunes.yaml
  config/crd/apiextensions.k8s.io/v1/base/k8up.io_restores.yaml
  config/crd/apiextensions.k8s.io/v1/base/k8up.io_schedules.yaml
  docs/modules/ROOT/examples/open-stack-swift-auth.yaml
  docs/modules/ROOT/examples/tutorial/backup.yaml
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/how-tos/generic-env-vars.adoc
  docs/modules/ROOT/pages/references/api-reference.adoc
  operator/executor/archive.go
  operator/executor/backup.go
  operator/executor/check.go
  operator/executor/prune.go
  operator/executor/restore.go
Labels: enhancement

#661 Ensure https is shown in code block in tutorial
  README.md
  docs/modules/ROOT/pages/tutorials/tutorial.adoc
Labels: documentation

#676 Fix panic when merging PodSecuritySontext from Schedule #638
  operator/handler/schedule.go
  operator/handler/schedule_test.go
Labels: bug

#666 Add additional port for webUI in tutorial
  docs/modules/ROOT/examples/tutorial/backup.yaml
  docs/modules/ROOT/examples/tutorial/minio/deployment.yaml
  docs/modules/ROOT/examples/tutorial/minio/service.yaml
  docs/modules/ROOT/examples/tutorial/scripts/6_stop.sh
  docs/modules/ROOT/examples/tutorial/scripts/environment.sh
  docs/modules/ROOT/pages/tutorials/tutorial.adoc
Labels: documentation

#682 Update Go to v1.18
  cmd/restic/integration_test.go
  controllers/backup_integration_test.go
  controllers/backup_it_utils_test.go
  controllers/check_integration_test.go
  controllers/restore_integration_test.go
  controllers/schedule_it_test.go
  controllers/schedule_it_utils_test.go
  envtest/envsuite.go
  go.mod
  go.sum
  operator/executor/cleaner/cleaner_integration_test.go
  tools.go
Labels: dependency
